theme: jekyll-theme-cayman

title: 追风逐月的博客
subtitle: 
description: 
author: haoxuebing
url: http://haoxuebing.github.io

# markdown: kramdown

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
